#include <vector>           // vector utils     |   std::vector , ...
#include <iostream>         // I/O operations   |   std::cout , ...
#include <chrono>           // time keeping     |   std::chrono, ... 

#include "sat.hpp"     // Build formula     |   ccsat::Formula, ...

int main(){

    std::string str = "f(a)=b&g(c,d)=b";
    ccsat::Sat s = ccsat::Sat(str);

    return 0;
}
